### PR TITLE
Use built-in dataclass instead of attrs

### PR DESCRIPTION
**Pull request by goncalossilva**

### CODE REVIEW

**Review by lefcha — APPROVED** [review]
LGTM!

**Comment by cdce8p** [comment]
Any update here? The restrictive `attrs` pin currently block Home Assistant from updating.
As an alternative, I've opened #97 to remove the upper bound for `attrs`.

Context: https://github.com/home-assistant/core/pull/97095

**Comment by goncalossilva** [comment]
Sorry for the delay, @cdce8p. I lost track of this. 😅

**Comment by goncalossilva** [comment]
@lefcha can I follow the steps [here](https://github.com/Doist/todoist-api-python#releases) to issue a new release?

**Comment by lefcha** [comment]
> @lefcha can I follow the steps [here](https://github.com/Doist/todoist-api-python#releases) to issue a new release?

@goncalossilva Yes, that should work: [.github/workflows/publish.yml](https://github.com/Doist/todoist-api-python/blob/869ad1fd02ed88bc42bc286caf682fe1ffe92ea3/.github/workflows/publish.yml)

**Pull request merged**
