### PR TITLE
feat: add sync read resources support

### PR DESCRIPTION
**Pull request by iloveitaly**

### CODE REVIEW

**Comment by odsamuels** [comment]
Does this look merge-ready @lefcha / @Doist/backend-hero ? 🙏

**Comment by lefcha** [comment]
This library is based on the REST API, and while we have an additional API call (the quick add) that is described in the [Sync API documentation](https://developer.todoist.com/sync/), it is really not part of `https://api.todoist.com/sync/v9/sync`.

We might add more API calls that are documented in the Sync API doc, but I'm not sure about adding support for the `sync` command itself.

CC @PotHix

**Comment by PotHix** [comment]
Yeah, I also agree with @lefcha, that was not the goal with this library. The `sync` endpoint has to be used in a sync way (sync, keep data locally, do partial syncs, etc.) and it's not something we envision with this library.

There's a chance we're going to unify our APIs at some point though, so we can expect that to happen in the future.

**Comment by iloveitaly** [comment]
@lefcha just created an issue here with more context https://github.com/Doist/todoist-api-python/issues/103

**Pull request closed without merging**
