### PR TITLE
build: set sensible timout

### PR DESCRIPTION
**Pull request by pkoch**
Based on historical data, clamped between 5 and 60.

See https://github.com/Doist/Issues/issues/5259

### CODE REVIEW

**Review by jankratochvilcz — APPROVED** [review]
Why so much? 60 minutes seems overly generous, 5 would be more like it 👀

**Comment by pkoch** [comment]
> Why so much? 60 minutes seems overly generous, 5 would be more like it 👀

Let's go with that, then! This is based on historical data, so some run might have gotten stuck or something.

I'm still rate limited, but you can take a look for yourself:
```bash
pkoch@gato:~/github.com/Doist/todoist-api-python
$  (     cd .github/workflows;      for WORKFLOW in `ls *.yml`; do       echo $WORKFLOW; gh run list --workflow $WORKFLOW;     done;   )
ci.yml
failed to get runs: HTTP 403: API rate limit exceeded for user ID 9627. (https://api.github.com/repos/Doist/todoist-api-python/actions/workflows/ci.yml)
publish.yml
failed to get runs: HTTP 403: API rate limit exceeded for user ID 9627. (https://api.github.com/repos/Doist/todoist-api-python/actions/workflows/publish.yml)
```

**Comment by scottlovegrove** [comment]
@pkoch Did you mean to merge this without changing the value down to 5?

**Comment by pkoch** [comment]
@scottlovegrove Sorry, I'm in robot mode. 😅 I'm pretty sure that value is safe, since it's based on the latest runs of the workflow.

If you feel confident that 5 is the right value, we can totally make that happen!

**Comment by scottlovegrove** [comment]
> If you feel confident that 5 is the right value, we can totally make that happen!

I'm basing it purely on Igor's comment 😄 If he is ok with 60, then I'm ok with 60, but I just wanted to check that this was what we were going with.

**Comment by pkoch** [comment]
@scottlovegrove Igor is not on this PR. Perhaps you're crossing wires? 😅

**Comment by scottlovegrove** [comment]
> @scottlovegrove Igor is not on this PR. Perhaps you're crossing wires? 😅

I just assumed we'd be using the same values across the board here (as they were all 60), so took what he put in the other PR as the way forward.

**Comment by pkoch** [comment]
Happy to use any other value that makes sense. :)

**Pull request merged**
